# Generated by Django 2.2.19 on 2021-04-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'College',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cname', models.CharField(db_column='CName', max_length=50, primary_key=True, serialize=False)),
                ('room_num', models.CharField(blank=True, db_column='Room_Num', max_length=50, null=True)),
                ('professor', models.CharField(db_column='Professor', max_length=50)),
                ('num_credits', models.IntegerField(db_column='Num_Credits')),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dname', models.CharField(db_column='DName', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_credits', models.IntegerField(db_column='Current_Credits')),
            ],
            options={
                'db_table': 'Enrolled',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_number', models.IntegerField(db_column='ID_Number', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
            ],
            options={
                'db_table': 'Login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, db_column='Message_Text', null=True)),
                ('time_sent', models.DateTimeField(blank=True, db_column='Time_Sent', null=True)),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cname', models.CharField(db_column='CName', max_length=50)),
                ('sname', models.CharField(db_column='SName', max_length=50, primary_key=True, serialize=False)),
                ('semester', models.CharField(db_column='Semester', max_length=50)),
                ('seats_left', models.IntegerField(db_column='Seats_Left')),
            ],
            options={
                'db_table': 'Section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Login')),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Login')),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Advisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Login')),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Student')),
                ('degree_program', models.CharField(blank=True, db_column='Degree_Program', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Graduate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Undergraduate',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Student')),
                ('class_year', models.CharField(blank=True, db_column='Class_Year', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Undergraduate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Undergraduate')),
                ('major_name', models.CharField(blank=True, db_column='Major_Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Majors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minors',
            fields=[
                ('id_number', models.OneToOneField(db_column='ID_Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Undergraduate')),
                ('minor_name', models.CharField(blank=True, db_column='Minor_Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Minors',
                'managed': False,
            },
        ),
    ]
